version: '3'
#name: ${CONTAINER_NAME}
services:
    app:
        build:
            args:
                user: "${UID}:${GID}"
                uid: ${UID}
            context: ./
            dockerfile: Dockerfile
        image: wordpress_base_image:latest
        container_name: ${CONTAINER_NAME}_app
        restart: unless-stopped
        tty: true
        user: "${UID}:${GID}"
        environment:
            SERVICE_NAME: ${CONTAINER_NAME}
            SERVICE_TAGS: ${APP_ENV}
            CONTAINER_ROLE: app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx:latest
        container_name: ${CONTAINER_NAME}_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "${WEBSERVER_HTTP_PORT}:80"
            - "${WEBSERVER_HTTPS_PORT}:443"
        links:
            - app
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - /var/certs/:/var/certs/
        networks:
            - app-network

    db:
        image: mysql:latest
        container_name: ${CONTAINER_NAME}_db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            # MYSQL_RANDOM_ROOT_PASSWORD: 1
            SERVICE_TAGS: ${APP_ENV}
            SERVICE_NAME: ${DB_DATABASE}
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: ${CONTAINER_NAME}_phpmyadmin
        restart: always
        links:
            - db
        depends_on:
            - db
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${CONTAINER_NAME}_db
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - UPLOAD_LIMIT=600M
        volumes:
            - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local

